'''
System models rebuilt with lumped vessels: a copy of a system model whose vessels with a
<version>_lumped twin use it, converted by libcuflynx.utilities.lumped_migration (shared
parameters keep their names; computed ones become <var>_<vessel>_<submodule>; outputs
<vessel>/<var> become <vessel>_<submodule>/<var>). The copy must reproduce the original
(supermodule.equivalent in the spec of the _lumped version named in LUMPED_SYSTEMS).
'''
import os
import shutil

import yaml

from cam_testing.library import MODULES_DIR, REPO_ROOT
from cam_testing import system as systems

SYSTEMS_DIR = os.path.join(REPO_ROOT, 'system_models')

# (source system model, new name, the _lumped version whose spec holds the equivalence entry)
LUMPED_SYSTEMS = [('closed_loop_cvs/3compartment', '3compartment_lumped', ('arterial_simple', 'vp_lumped'))]


def build(source, name):
    '''Writes system_models/<category>/<name>; returns (system dir, the equivalence entry).'''
    from libcuflynx.utilities.lumped_migration import Library, migrate_files
    from cam_testing import vessel_array
    category, src_name = source.split('/')
    src = os.path.join(SYSTEMS_DIR, category, src_name)
    dst = os.path.join(SYSTEMS_DIR, category, name)
    if os.path.isdir(dst):
        shutil.rmtree(dst)
    os.makedirs(dst)
    result = migrate_files(Library([MODULES_DIR]), os.path.join(src, f'{src_name}_vessel_array.json'),
                           os.path.join(src, f'{src_name}_parameters.csv'), out_dir=dst, prefix=name,
                           old_prefix=src_name)
    records = vessel_array.read_records(os.path.join(src, f'{src_name}_vessel_array.json'))
    replaced = sorted(result['replaced'])
    src_spec = systems.load_system(src_name).spec
    spec = {
        'model': name, 'category': category, 'reviewed': False,
        'sim_time': src_spec.get('sim_time', 2.0), 'pre_time': src_spec.get('pre_time', 0.0),
        'dt': src_spec.get('dt', 0.01),
        'equivalence': {'status': 'not_applicable',
                        'reason': f'built from this library only: supermodule_equivalence_test compares it with '
                                  f'{source} (the same model with the monolithic vessels)'},
        'invariants': src_spec.get('invariants') or [],
        'notes': [f'{source} with its vessels {", ".join(replaced)} replaced by their _lumped supermodule versions '
                  '(compliance, resistance and inertance submodules from modules/haemodynamics/lumped_constitutive), '
                  'converted by libcuflynx.utilities.lumped_migration. Generated by tools/lumped/systems.py.'],
    }
    with open(os.path.join(dst, f'{name}_system.yaml'), 'w') as f:
        yaml.safe_dump(spec, f, sort_keys=False, width=120)
    entry = {'model': f'{category}/{name}', 'reproduces': source, 'replaced_vessels': replaced,
             'output_map': {o: o for o in result['outputs']}, 'tol': 1e-6, 'solver_info': {'rtol': 1e-10, 'atol': 1e-14},
             'ignore': {f'{r["name"]}/t': 'time' for r in records}}
    # the heart's sawtooth phases and the valves' near-singular inertances, compared as the
    # supermodule heart's system test compares them
    chambers = [r['name'] for r in records if r['module_type'] == 'chamber']
    valves = [r['name'] for r in records if r['module_type'] == 'valve']
    if chambers:
        entry['wrapped'] = {f'{c}/{v}': 1.0 for c in chambers for v in ('chi_floor', 'chi_floor_final')}
    if valves:
        entry['reciprocal'] = [f'{v}/{x}' for v in valves for x in ('L', 'B')]
    return dst, entry


def equivalence_entries():
    '''{(module_type, version): [supermodule.equivalent entries]}, building the system models.'''
    out = {}
    for source, name, holder in LUMPED_SYSTEMS:
        _, entry = build(source, name)
        out.setdefault(holder, []).append(entry)
    return out
