'''
Writes the lumped constitutive modules (tools/lumped/constitutive.py) and the vessel supermodules
built from them (tools/lumped/vessels.py) into the module library.

    python -m tools.lumped.write              # constitutive versions, vessel supermodules, templates
    python -m tools.lumped.write --constitutive-only
'''
import argparse
import csv
import glob
import json
import os
import re
import shutil

from cam_testing.library import MODULES_DIR, write_spec

from . import mathml as m
from .constitutive import ALL

CONSTITUTIVE_DIR = os.path.join(MODULES_DIR, 'haemodynamics', 'lumped_constitutive')
BUILTIN_UNITS = {'second', 'dimensionless', 'metre', 'joule', 'kilogram'}
GENERATED_NOTE = 'Generated by tools/lumped/write.py from tools/lumped/constitutive.py; edit those, not this file.'
DEFAULT_REFERENCE = 'cam_testing: generic default (a representative large-artery value), not sourced'


def _units_library():
    '''Every <units> definition in the library, by name.'''
    units = {}
    for path in sorted(glob.glob(os.path.join(MODULES_DIR, '**', '*_units.cellml'), recursive=True)):
        with open(path) as f:
            text = f.read()
        for match in re.finditer(r'<units name="([^"]+)">.*?</units>', text, re.S):
            units.setdefault(match.group(1), match.group(0))
    return units


def _bib():
    with open(os.path.join(MODULES_DIR, 'vessels', 'compartments', 'arterial_simple', 'versions', 'vp',
                           'arterial_simple_vp_references.bib')) as f:
        text = f.read()
    return text[:text.index('\n}\n') + 3] if '\n}\n' in text else text


def write_json(path, data):
    with open(path, 'w') as f:
        json.dump(data, f, indent=2)
        f.write('\n')


def write_instance(vdir, rows, name='default'):
    idir = os.path.join(vdir, 'instances', name)
    os.makedirs(idir, exist_ok=True)
    with open(os.path.join(idir, f'{name}_parameters.csv'), 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['variable_name', 'units', 'value', 'data_reference', 'sourced'])
        writer.writerows(rows)


def fresh_version_dir(module_dir, version):
    vdir = os.path.join(module_dir, 'versions', version)
    if os.path.isdir(vdir):
        shutil.rmtree(vdir)
    os.makedirs(vdir)
    return vdir


def write_constitutive(v, units_library, bib):
    vdir = fresh_version_dir(os.path.join(CONSTITUTIVE_DIR, v.module_type), v.version)
    stem = f'{v.module_type}_{v.version}'
    interface = {'variable': 'out'}
    cellml_vars = [('t', 'second', 'in', None)]
    for var in v.variables:
        cellml_vars.append((var.name, var.units, interface.get(var.kind, 'in'), var.initial))
    with open(os.path.join(vdir, f'{stem}_modules.cellml'), 'w') as f:
        f.write(m.model(stem, [m.component(v.component, cellml_vars, v.equations)]))
    used = {var.units for var in v.variables} - BUILTIN_UNITS
    with open(os.path.join(vdir, f'{stem}_units.cellml'), 'w') as f:
        f.write("<?xml version='1.0' encoding='UTF-8'?>\n<model name=\"Units\" "
                'xmlns="http://www.cellml.org/cellml/1.1#" xmlns:cellml="http://www.cellml.org/cellml/1.1#">\n')
        for u in sorted(used):
            f.write('    ' + units_library[u] + '\n')
        f.write('</model>\n')
    write_json(os.path.join(vdir, f'{stem}_modules_config.json'), [{
        'module_type': v.module_type, 'module_subtype': v.version, 'module_format': 'cellml',
        'component_file': f'{stem}_modules.cellml', 'component_type': v.component,
        'default_instance': 'default', 'licence': 'CC0-1.0', 'creator': [], 'description': v.description,
        'entrance_ports': v.entrance_ports, 'exit_ports': v.exit_ports, 'general_ports': [],
        'variables_and_units': [[var.name, var.units, 'access', var.kind] for var in v.variables]}])
    write_instance(vdir, [[var.name, var.units, var.default, DEFAULT_REFERENCE, 'no'] for var in v.variables
                          if var.kind != 'variable'])
    write_spec(vdir, stem, {
        'module_type': v.module_type, 'version': v.version, 'reviewed': False, 'description': v.description,
        'notes': GENERATED_NOTE, 'sim_time': v.sim_time, 'pre_time': 0.0, 'dt': v.dt, 'solver': 'CVODE_myokit',
        'solver_info': {'rtol': 1e-7, 'atol': 1e-12}, 'reference_solver_info': {'rtol': 1e-10, 'atol': 1e-14},
        'outputs': v.outputs, 'run_parameters': {}})
    with open(os.path.join(vdir, f'{stem}_references.bib'), 'w') as f:
        f.write(bib)
    return vdir


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--constitutive-only', action='store_true')
    parser.add_argument('--only', action='append', help='<module_type>/<version> of a monolithic vessel (repeatable)')
    args = parser.parse_args(argv)
    units_library, bib = _units_library(), _bib()
    for v in ALL:
        write_constitutive(v, units_library, bib)
    print(f'{len(ALL)} constitutive versions in {os.path.relpath(CONSTITUTIVE_DIR)}')
    if not args.constitutive_only:
        from . import vessels
        vessels.write_all(units_library, bib, only=args.only)


if __name__ == '__main__':
    main()
