"""
The module library on disk: finding modules, and reading each module's config, parameters
and test spec.

Layout (one directory per CellML module file):

    modules/<name>/<name>_modules.cellml
    modules/<name>/<name>_modules_config.json
    modules/<name>/<name>_units.cellml
    modules/<name>/<name>_parameters.csv
    modules/<name>/<name>_tests.yaml
    modules/<name>/validation/                 baseline / calibration data
    modules/<name>/plots/, results/            generated by the tests (gitignored)
"""
import copy
import csv
import json
import os
import re
from dataclasses import dataclass, field

import yaml

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODULES_DIR = os.path.join(REPO_ROOT, 'modules')


def module_names():
    '''Modules that have a test spec, in case-insensitive order.'''
    if not os.path.isdir(MODULES_DIR):
        return []
    return sorted((d for d in os.listdir(MODULES_DIR)
                   if os.path.isfile(os.path.join(MODULES_DIR, d, f'{d}_tests.yaml'))),
                  key=str.lower)


def deep_merge(base, override):
    out = copy.deepcopy(base)
    for key, value in (override or {}).items():
        if isinstance(value, dict) and isinstance(out.get(key), dict):
            out[key] = deep_merge(out[key], value)
        else:
            out[key] = copy.deepcopy(value)
    return out


def safe_id(text):
    '''A filesystem/URL-safe id for a component, e.g. for plot filenames.'''
    return re.sub(r'[^A-Za-z0-9_.-]+', '_', text)


PARAMETER_COLUMNS = ['vessel_type', 'BC_type', 'variable_name', 'units', 'value', 'kind', 'data_reference',
                     'sourced']

# data_reference text that does not cite a source (assumptions, tuning, placeholders, TODOs)
import re as _re
UNSOURCED_PATTERN = _re.compile(
    r'(^$|^none$|^test$|^known$|todo|to_do|to_be|user|defined_by|placeholder|prototype|identified|'
    r'assum|wont_be|not_used|hand.?tuned|tuned|chosen|check|calculated|calc_|from_icu|nonstiff|'
    r'initial_guess|rate_constant|cam_testing|circulatory_autogen example)', _re.I)


def looks_sourced(reference):
    '''Heuristic for seeding the sourced column: does the reference cite a source?'''
    ref = (reference or '').strip()
    if ':' in ref and not ref.lower().startswith('circulatory_autogen'):
        ref = ref.split(':', 1)[1].strip()   # "<CA example model>: <reference>" from the importer
    return not UNSOURCED_PATTERN.search(ref)


@dataclass
class Parameter:
    vessel_type: str
    BC_type: str
    variable_name: str
    units: str
    value: str
    kind: str
    data_reference: str
    sourced: str = ''

    @property
    def is_sourced(self):
        return self.sourced.strip().lower() in ('yes', 'true', '1')

    @property
    def is_todo(self):
        return self.value.strip().upper() == 'TODO'

    @property
    def float_value(self):
        return float(self.value)


@dataclass
class Component:
    module: 'Module'
    vessel_type: str
    BC_type: str
    module_type: str
    config: dict
    spec: dict

    @property
    def id(self):
        return safe_id(f'{self.vessel_type}__{self.BC_type}')

    @property
    def label(self):
        return f'{self.vessel_type} ({self.BC_type})'

    def parameters(self):
        '''The component's own constants / BCs, then the global constants it uses.'''
        own = [p for p in self.module.parameters
               if p.vessel_type == self.vessel_type and p.BC_type == self.BC_type]
        global_names = {v[0] for v in self.config['variables_and_units'] if v[3].strip() == 'global_constant'}
        glob = [p for p in self.module.parameters
                if p.vessel_type == 'global' and p.variable_name in global_names]
        return own + glob

    def unsourced_parameters(self):
        return [p.variable_name for p in self.parameters() if not p.is_sourced]

    def todo_parameters(self):
        return [p.variable_name for p in self.parameters() if p.is_todo]

    def boundary_conditions(self):
        return [p for p in self.parameters() if p.kind == 'boundary_condition']

    def variables(self):
        return [v for v in self.config['variables_and_units'] if v[3].strip() == 'variable']


@dataclass
class Module:
    name: str
    dir: str
    config: list
    spec: dict
    parameters: list = field(default_factory=list)

    @property
    def cellml_path(self):
        return os.path.join(self.dir, f'{self.name}_modules.cellml')

    @property
    def units_path(self):
        return os.path.join(self.dir, f'{self.name}_units.cellml')

    @property
    def plots_dir(self):
        return os.path.join(self.dir, 'plots')

    @property
    def results_dir(self):
        return os.path.join(self.dir, 'results')

    @property
    def validation_dir(self):
        return os.path.join(self.dir, 'validation')

    def all_sourced(self):
        return all(p.is_sourced for p in self.parameters)

    @property
    def reviewed(self):
        return bool(self.spec.get('reviewed', False))

    def components(self):
        config_by_key = {(e['vessel_type'], e['BC_type']): e for e in self.config}
        defaults = self.spec.get('defaults', {})
        out = []
        for comp_spec in self.spec.get('components', []):
            key = (comp_spec['vessel_type'], comp_spec['BC_type'])
            if key not in config_by_key:
                raise KeyError(f'{self.name}_tests.yaml lists {key}, which is not in the module config')
            entry = config_by_key[key]
            spec = deep_merge(defaults, comp_spec)
            out.append(Component(self, key[0], key[1], entry['module_type'], entry, spec))
        return out

    def component(self, component_id):
        for c in self.components():
            if c.id == component_id:
                return c
        raise KeyError(component_id)


def load_module(name):
    module_dir = os.path.join(MODULES_DIR, name)
    with open(os.path.join(module_dir, f'{name}_modules_config.json')) as f:
        config = json.load(f)
    spec_path = os.path.join(module_dir, f'{name}_tests.yaml')
    spec = {}
    if os.path.isfile(spec_path):
        with open(spec_path) as f:
            spec = yaml.safe_load(f) or {}
    parameters = []
    params_path = os.path.join(module_dir, f'{name}_parameters.csv')
    if os.path.isfile(params_path):
        with open(params_path, newline='') as f:
            for row in csv.DictReader(f):
                parameters.append(Parameter(**{k: (row.get(k) or '').strip() for k in Parameter.__dataclass_fields__}))
    return Module(name, module_dir, config, spec, parameters)
