"""
The module library on disk: finding modules, and reading each module's config, parameters
and test spec.

Layout (one directory per CellML module file):

    modules/<name>/<name>_modules.cellml
    modules/<name>/<name>_modules_config.json
    modules/<name>/<name>_units.cellml
    modules/<name>/<name>_parameters.csv
    modules/<name>/<name>_tests.yaml
    modules/<name>/validation/                 baseline / calibration data
    modules/<name>/plots/, results/            generated by the tests (gitignored)
"""
import functools
import copy
import csv
import json
import os
import re
from dataclasses import dataclass, field

import yaml

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODULES_DIR = os.path.join(REPO_ROOT, 'modules')


# Directories under modules/ that hold something other than modules
NON_MODULE_DIRS = ('system', 'supermodules', 'template')


@functools.lru_cache(maxsize=None)
def _module_dirs():
    '''name -> directory, for every modules/**/<name>/ that has <name>_tests.yaml. Modules may be
    grouped in category directories (e.g. modules/cell/neurons/); names are unique.'''
    found = {}
    for root, dirs, files in os.walk(MODULES_DIR):
        rel = os.path.relpath(root, MODULES_DIR)
        if rel.split(os.sep)[0] in NON_MODULE_DIRS:
            dirs[:] = []
            continue
        dirs[:] = sorted(d for d in dirs if not d.startswith('.') and d not in ('plots', 'results', 'risk', 'validation'))
        name = os.path.basename(root)
        if f'{name}_tests.yaml' in files:
            if name in found:
                raise ValueError(f'two modules are called {name}: {found[name]} and {root}')
            found[name] = root
    return found


def module_names():
    '''Modules that have a test spec, in case-insensitive order.'''
    if not os.path.isdir(MODULES_DIR):
        return []
    return sorted(_module_dirs(), key=str.lower)


def module_dir(name):
    '''The directory of a module (modules/<name>/, or modules/<category>/<name>/).'''
    dirs = _module_dirs()
    return dirs.get(name) or os.path.join(MODULES_DIR, name)


def module_relpath(name):
    '''The module's directory relative to modules/, e.g. "cell/neurons".'''
    return os.path.relpath(module_dir(name), MODULES_DIR)


def deep_merge(base, override):
    out = copy.deepcopy(base)
    for key, value in (override or {}).items():
        if isinstance(value, dict) and isinstance(out.get(key), dict):
            out[key] = deep_merge(out[key], value)
        else:
            out[key] = copy.deepcopy(value)
    return out


def safe_id(text):
    '''A filesystem/URL-safe id for a component, e.g. for plot filenames.'''
    return re.sub(r'[^A-Za-z0-9_.-]+', '_', text)


PARAMETER_COLUMNS = ['vessel_type', 'BC_type', 'variable_name', 'units', 'value', 'kind', 'data_reference',
                     'sourced']

# data_reference text that does not cite a source (assumptions, tuning, placeholders, TODOs)
import re as _re
UNSOURCED_PATTERN = _re.compile(
    r'(^$|^none$|^test$|^known$|todo|to_do|to_be|user|defined_by|placeholder|prototype|identified|'
    r'assum|wont_be|not_used|hand.?tuned|tuned|chosen|check|calculated|calc_|from_icu|nonstiff|'
    r'initial_guess|rate_constant|cam_testing|circulatory_autogen example)', _re.I)


def looks_sourced(reference):
    '''Heuristic for seeding the sourced column: does the reference cite a source?'''
    ref = (reference or '').strip()
    if ':' in ref and not ref.lower().startswith('circulatory_autogen'):
        ref = ref.split(':', 1)[1].strip()   # "<CA example model>: <reference>" from the importer
    return not UNSOURCED_PATTERN.search(ref)


@dataclass
class Parameter:
    vessel_type: str
    BC_type: str
    variable_name: str
    units: str
    value: str
    kind: str
    data_reference: str
    sourced: str = ''
    proposed: bool = False          # value comes from a review proposal (not in the parameters file yet)

    @property
    def is_sourced(self):
        return self.sourced.strip().lower() in ('yes', 'true', '1')

    @property
    def is_todo(self):
        return self.value.strip().upper() == 'TODO'

    @property
    def float_value(self):
        return float(self.value)


@dataclass
class Component:
    module: 'Module'
    vessel_type: str
    BC_type: str
    module_type: str
    config: dict
    spec: dict

    @property
    def id(self):
        return safe_id(f'{self.vessel_type}__{self.BC_type}')

    @property
    def label(self):
        return f'{self.vessel_type} ({self.BC_type})'

    def parameters(self):
        '''The component's own constants / BCs, then the global constants it uses.'''
        own = [p for p in self.module.parameters
               if p.vessel_type == self.vessel_type and p.BC_type == self.BC_type]
        global_names = {v[0] for v in self.config['variables_and_units'] if v[3].strip() == 'global_constant'}
        glob = [p for p in self.module.parameters
                if p.vessel_type == 'global' and p.variable_name in global_names]
        return own + glob

    def unsourced_parameters(self):
        return [p.variable_name for p in self.parameters() if not p.is_sourced]

    def todo_parameters(self):
        return [p.variable_name for p in self.parameters() if p.is_todo]

    def boundary_conditions(self):
        return [p for p in self.parameters() if p.kind == 'boundary_condition']

    def variables(self):
        return [v for v in self.config['variables_and_units'] if v[3].strip() == 'variable']


@dataclass
class Module:
    name: str
    dir: str
    config: list
    spec: dict
    parameters: list = field(default_factory=list)

    @property
    def cellml_path(self):
        return os.path.join(self.dir, f'{self.name}_modules.cellml')

    @property
    def units_path(self):
        return os.path.join(self.dir, f'{self.name}_units.cellml')

    @property
    def plots_dir(self):
        return os.path.join(self.dir, 'plots')

    @property
    def results_dir(self):
        return os.path.join(self.dir, 'results')

    @property
    def validation_dir(self):
        return os.path.join(self.dir, 'validation')

    def all_sourced(self):
        return all(p.is_sourced for p in self.parameters)

    @property
    def reviewed(self):
        return bool(self.spec.get('reviewed', False))

    def components(self):
        config_by_key = {(e['vessel_type'], e['BC_type']): e for e in self.config}
        defaults = self.spec.get('defaults', {})
        out = []
        for comp_spec in self.spec.get('components', []):
            key = (comp_spec['vessel_type'], comp_spec['BC_type'])
            if key not in config_by_key:
                raise KeyError(f'{self.name}_tests.yaml lists {key}, which is not in the module config')
            entry = config_by_key[key]
            spec = deep_merge(defaults, comp_spec)
            out.append(Component(self, key[0], key[1], entry['module_type'], entry, spec))
        return out

    def component(self, component_id):
        for c in self.components():
            if c.id == component_id:
                return c
        raise KeyError(component_id)


# Module configs come in two formats: PhLynx's (this library's) and libcuflynx's original.
# Both are read; code here uses libcuflynx's internal names. module_type means different things in
# the two, so the format is told by the other keys, never by module_type.
PHLYNX_KEYS = {'module_type': 'vessel_type', 'module_subtype': 'BC_type',
               'component_file': 'module_file', 'component_type': 'module_type'}
LIBCUFLYNX_KEYS = ('vessel_type', 'BC_type', 'module_file', 'module_type')


def is_supermodule(entry):
    return entry.get('module_format') == 'supermodule'


def config_format(entry):
    if is_supermodule(entry):
        # a supermodule has no CellML component: only its type/subtype keys tell the style
        return 'libcuflynx' if {'vessel_type', 'BC_type'} & set(entry) else 'phlynx'
    phlynx = {'module_subtype', 'component_file', 'component_type'} & set(entry)
    libcuflynx = {'vessel_type', 'BC_type', 'module_file'} & set(entry)
    if phlynx and libcuflynx:
        raise ValueError(f'config entry mixes PhLynx keys {sorted(phlynx)} with libcuflynx keys {sorted(libcuflynx)}')
    if phlynx:
        missing = set(PHLYNX_KEYS) - set(entry)
        if missing:
            raise ValueError(f'PhLynx-format config entry is missing {sorted(missing)}')
        return 'phlynx'
    missing = set(LIBCUFLYNX_KEYS) - set(entry)
    if missing:
        raise ValueError(f'config entry is missing {sorted(missing)} (neither PhLynx nor libcuflynx format)')
    return 'libcuflynx'


def normalise_config_entry(entry):
    '''A config entry in either format -> libcuflynx's names (other keys unchanged).'''
    if config_format(entry) == 'libcuflynx':
        return dict(entry)
    if is_supermodule(entry):
        out = {k: v for k, v in entry.items() if k not in ('module_type', 'module_subtype')}
        return {'vessel_type': entry['module_type'], 'BC_type': entry['module_subtype'], **out}
    out = {k: v for k, v in entry.items() if k not in PHLYNX_KEYS}
    out.update({internal: entry[k] for k, internal in PHLYNX_KEYS.items()})
    return out


def to_phlynx_entry(entry):
    '''A config entry in either format -> PhLynx's key names, in PhLynx's key order.'''
    e = normalise_config_entry(entry)
    head = {'module_type': e['vessel_type'], 'module_subtype': e['BC_type'], 'module_format': e.get('module_format'),
            'component_file': e['module_file'], 'component_type': e['module_type']}
    if head['module_format'] is None:
        del head['module_format']
    return {**head, **{k: v for k, v in e.items() if k not in LIBCUFLYNX_KEYS and k != 'module_format'}}


def read_config(path):
    with open(path) as f:
        return [normalise_config_entry(e) for e in json.load(f)]


def load_module(name):
    mdir = module_dir(name)
    config = read_config(os.path.join(mdir, f'{name}_modules_config.json'))
    spec_path = os.path.join(mdir, f'{name}_tests.yaml')
    spec = {}
    if os.path.isfile(spec_path):
        with open(spec_path) as f:
            spec = yaml.safe_load(f) or {}
    parameters = []
    params_path = os.path.join(mdir, f'{name}_parameters.csv')
    if os.path.isfile(params_path):
        with open(params_path, newline='') as f:
            for row in csv.DictReader(f):
                parameters.append(Parameter(**{k: (row.get(k) or '').strip() for k in PARAMETER_COLUMNS}))
    # A TODO value with a proposed value in the spec's reference_proposals is used (marked
    # proposed) so a module prepared for review can be tested before the proposal is applied.
    for comp in spec.get('components', []):
        for var, prop in (comp.get('reference_proposals') or {}).items():
            if not isinstance(prop, dict) or 'value' not in prop:
                continue
            for p in parameters:
                if p.variable_name == var and p.is_todo and (
                        (p.vessel_type, p.BC_type) == (comp['vessel_type'], comp['BC_type']) or p.vessel_type == 'global'):
                    p.value, p.proposed = str(prop['value']), True
    return Module(name, mdir, config, spec, parameters)
